# ╔════════════════════════════════════════════════════════════════════════════════╗
# ║                                                                                ║
# ║                Bienvenue dans la configuration de Liens                        ║
# ║                                                                                ║
# ╚════════════════════════════════════════════════════════════════════════════════╝

# Mettez le lien de votre serveur discord et le message que vous voulez entre les guillemets. Pour les couleurs, utilisez le symbole § au lieu du symbole &
discord:
  message: "§a[§2!§&] §eVous n'avez pas spécifié votre message. Rendez vous dans le dossier §6plugins/Liens §ede votre serveur, dans le fichier §6config.yml §eet modifiez tout ça"

# Mettez le lien de votre site web et le message que vous voulez entre les guillemets. Pour les couleurs, utilisez le symbole § au lieu du symbole &
site: 
  message: "§a[§2!§&] §eVous n'avez pas spécifié votre message. Rendez vous dans le dossier §6plugins/Liens §ede votre serveur, dans le fichier §6config.yml §eet modifiez tout ça"

# Mettez le lien de votre règlement et le message que vous voulez entre les guillemets. Pour les couleurs, utilisez le symbole § au lieu du symbole &
reglement:
  message: "§a[§2!§&] §eVous n'avez pas spécifié votre message. Rendez vous dans le dossier §6plugins/Liens §ede votre serveur, dans le fichier §6config.yml §eet modifiez tout ça"

# Mettez le lien de votre serveur teamspeak et le message que vous voulez entre les guillemets. Pour les couleurs, utilisez le symbole § au lieu du symbole &
teamspeak:
  message: "§a[§2!§&] §eVous n'avez pas spécifié votre message. Rendez vous dans le dossier §6plugins/Liens §ede votre serveur, dans le fichier §6config.yml §eet modifiez tout ça"
  
# Mettez le lien de votre forum et le message que vous voulez entre les guillemets. Pour les couleurs, utilisez le symbole § au lieu du symbole &
forum:
  message: "§a[§2!§&] §eVous n'avez pas spécifié votre message. Rendez vous dans le dossier §6plugins/Liens §ede votre serveur, dans le fichier §6config.yml §eet modifiez tout ça"

# Mettez le lien de votre forum et le message que vous voulez entre les guillemets. Pour les couleurs, utilisez le symbole § au lieu du symbole &
twitter:
  message: "§a[§2!§&] §eVous n'avez pas spécifié votre message. Rendez vous dans le dossier §6plugins/Liens §ede votre serveur, dans le fichier §6config.yml §eet modifiez tout ça"