name: Liens
version: 1.0.1
author: Formicida
main: fr.formicida.liens.Liens
commands:
  discord:
    description: cette commande permet d'afficher le lien du serveur discord
    permission: liens.discord
  site:
    description: cette commande affiche le lien du site web
    permission: liens.site
  reglement:
    description: cette commande affiche le lien du reglement du serveur
    permission: liens.reglement
  liens:
    description: cette commande affiche les informations sur le plugin
    permission: liens.use
  teamspeak:
    description: cette commande affiche le lien du serveur teamspeak
    permission: liens.teamspeak
  forum:
    description: cette commande affiche le lien du forum
    permission: liens.forum
  twitter:
    description: cette commande affiche le lien du compte twitter
    permission: liens.twitter